### ISSUE TITLE
The dashbord did not show the name of the agreements

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#37] opened 2017-03-13 20:28 UTC
snap revision 75,  rpi2 on staging.  The device has been running for 4 days.
The dashboard shows 3 agreements,  one is "Executing" and the other 2 are "Available for Agreement". The agreement names are all shown as "Compute Resources".

**Comment by linggao** [comment] 2017-03-13 20:32
![status](https://cloud.githubusercontent.com/assets/12394418/23874043/a412ac10-080a-11e7-9a52-d50c4e839807.png)

**Comment by bmpotter** [comment] 2017-03-14 12:55
I've seen this behavior too. It seems to be when i have not done the registration thru the browser (i've done it on the cmd line thru the reg_all script), and then come to the UI just to see the dashboard. But my guess is that the same issue can be recreated by doing the registration in 1 browser, and then viewing the dashboard in another browser (or after rebooting your laptop).

**Comment by michaeldye** [comment] 2017-03-14 13:48
The rendered name is the "label" field of the compute attribute type. Please determine that this is not caused by registering with scripts that set this field to the value "Compute Resources".

**Comment by bmpotter** [comment] 2017-03-14 14:18
Ling, i think mike is correct. The reg_all json files have in them `"label": "Compute Resources"`. So i assigned this issue to you to fix.

Plus, just for completeness, i did the test i mentioned above (registered with 1 browser and viewed the dashboard with another browser) and it displayed the poc labels correctly.

**Comment by linggao** [comment] 2017-03-14 17:55
@michaeldye  should the UI use the lable fields of the app meta data instead of compute meta data? My understanding is that compute meta, location meta data and arch meta data are not unique to a service. They can be shared among the services. But app meta data is unique to a service because it has the app related attributes. 
````{
  "attributes": [
    {
      "id": "app",
      "sensor_urls": [
        "https://bluehorizon.network/documentation/location-device-api"
      ],
      "label": "app",
      "publishable": true,
      "mappings": {
        "HZN_GPS": "true",
        "MTN_GPS": "true"
      }
    },
    {
      "id": "app",
      "sensor_urls": [
        "https://bluehorizon.network/documentation/netspeed-device-api"
      ],
      "label": "app",
      "publishable": true,
      "mappings": {
        "HZN_IS_BANDWIDTH_TEST_ENABLED": "true",
        "HZN_TARGET_SERVER": "closest",
        "MTN_IS_BANDWIDTH_TEST_ENABLED": "true",
        "MTN_TARGET_SERVER": "closest"
      }
    },
    {
      "id": "architecture",
      "sensor_urls": [
        "https://bluehorizon.network/documentation/location-device-api"
      ],
      "label": "Architecture",
      "publishable": true,
      "mappings": {
        "architecture": "arm"
      }
    },
    {
      "id": "architecture",
      "sensor_urls": [
        "https://bluehorizon.network/documentation/netspeed-device-api"
      ],
      "label": "Architecture",
      "publishable": true,
      "mappings": {
        "architecture": "arm"
      }
    },
   {
      "id": "compute",
      "sensor_urls": [
        "https://bluehorizon.network/documentation/location-device-api"
      ],
      "label": "Compute Resources",
      "publishable": true,
      "mappings": {
        "cpus": 1,
        "ram": 128
      }
    },
    {
      "id": "compute",
      "sensor_urls": [
        "https://bluehorizon.network/documentation/netspeed-device-api"
      ],
      "label": "Compute Resources",
      "publishable": true,
      "mappings": {
        "cpus": 1,
        "ram": 128
      }
    },
    {
      "id": "location",
      "sensor_urls": [],
      "label": "Registered Location Facts",
      "publishable": false,
      "mappings": {
        "lat": "50.677",
        "lon": "-100.8619",
        "use_gps": false,
        "user_provided_coords": true
      }
    }
  ]
}
````

**Comment by michaeldye** [comment] 2017-03-14 20:39
The app metadata is just for compatibility with the old workloads; a new workload that doesn't need those special attributes would be defined by the compute resources it uses and wouldn't need any other attributes. Have a look at this JavaScript if you want to see how the UI does the registration of attributes: https://github.com/open-horizon/anax-ui/blob/master/src/actions/servicesRequests.js

**Closed** 2017-04-03 14:10 UTC
Labels: bug, ready for prod
